// src/components/Card.vue
<script setup lang="ts">
defineProps<{
    card: {
        name: string,
        cardImage: string,
        clicked: boolean,
    }, clickHandler: () => void
}>()

</script>

<template>
    <div className="single-card" v-on:click="clickHandler">
        <img :src="card.cardImage" :alt="card.name" class="undraggable" />
    </div>
</template>

<style scoped></style>

// src/Components/Card/Card.jsx
import "./Card.css"
export default function Card(props) {
  const { name, cardImage } = props.card
  return (
    <div className="single-card" onClick={() => props.clickHandler()}>
      <img
        src={`${cardImage}`}
        alt={name}
        className="undraggable"
        style={{
          width: `${props.imgWidth}rem`,
        }}
      />
    </div>
  )
}
