// src/Components/Cards/Cards.tsx
import "./Cards.css"
import { useState, useEffect } from "react"
import Card from "../Card/Card"
import { ICard } from "../../App"

export default function Cards({
  cards,
  rows,
  cols,
  newGame,
  cardArrayCleaner,
}: {
  cards: ICard[]
  rows: number
  cols: number
  newGame: () => void
  cardArrayCleaner: () => void
}) {
  const [gameCardsArray, setGameCardsArray] = useState<ICard[]>(cards)
  const [round, setRound] = useState<number>(1)
  const [won, setWon] = useState<boolean>(false)
  const [lost, setLost] = useState<boolean>(false)
  const [twiceClickedCard, setTwiceClickedCard] = useState<string>("")

  let imgWidth: number
  if (rows === 2) {
    imgWidth = 12
  } else if (rows === 3) {
    imgWidth = 8
  } else {
    imgWidth = 6
  }

  const arrayShuffler = (array: ICard[]) => {
    let shuffledArray: ICard[] = []
    let usedIndexes: number[] = []

    let i = 0
    while (i < array.length) {
      const RandNum = Math.floor(Math.random() * array.length)
      if (!usedIndexes.includes(RandNum)) {
        shuffledArray.push(array[RandNum])
        usedIndexes.push(RandNum)
        i++
      }
    }
    return shuffledArray
  }

  const cardClickHandler = (card: ICard) => {
    if (card.clicked) {
      setLost(true)
      setTwiceClickedCard(card.name)
    }
    const newArray = gameCardsArray.map((crd) =>
      crd.name === card.name ? { ...crd, clicked: true } : crd
    )

    setGameCardsArray(arrayShuffler(newArray))
    setRound((prevRound) => prevRound + 1)
  }

  useEffect(() => {
    if (gameCardsArray.every((card) => card.clicked)) {
      setWon(true)
    }
  }, [gameCardsArray])

  return (
    <div>
      {!won && !lost ? (
        <>
          {round === 1 ? (
            <p>
              You created a {rows} x {cols} grid, good luck! Round {round} /{" "}
              {rows * cols}{" "}
            </p>
          ) : (
            <p>
              Round {round} / {rows * cols}{" "}
            </p>
          )}
          <div
            id="cards-grid"
            style={{
              gridTemplateColumns: `repeat(${cols}, 1fr)`,
              gridTemplateRows: `repeat(${rows}, 1fr)`,
            }}
          >
            {gameCardsArray.map((card) => (
              <Card
                key={card.name}
                card={card}
                imgWidth={imgWidth}
                clickHandler={() => cardClickHandler(card)}
              />
            ))}
          </div>
        </>
      ) : lost ? (
        <>
          <p>
            You lost in round {round - 1} ,{" "}
            {twiceClickedCard[0].toUpperCase() + twiceClickedCard.slice(1)} was
            clicked once
          </p>
          <button
            onClick={() => {
              setWon(false)
              newGame()
              cardArrayCleaner()
              setRound(1)
            }}
            className="another-game"
          >
            Play another game
          </button>
        </>
      ) : (
        <>
          <p>You won</p>
          <button
            onClick={() => {
              setWon(false)
              cardArrayCleaner()
              newGame()
              setRound(1)
            }}
            className="another-game"
          >
            Play another game
          </button>
        </>
      )}
    </div>
  )
}

// src/components/Cards.vue
<script setup lang="ts">
import { ref, watchEffect } from 'vue'
import Card from './Card.vue';
import { ICard } from '../App.vue';

const props = defineProps<{ rows: number, cols: number, newGame: () => void }>()

const gameCardsArray = ref([])
const round = ref(1)
const lost = ref(false)
const won = ref(false)
const twiceClickedCard = ref("")

const fetchData = async () => {

  const error = ref<string>('');
  const data = ref<any>([]);
  const tempArr: any = []
  let randomi = Math.floor(Math.random() * 752) + 1
  for (let i = randomi; i < randomi + (props.cols * props.rows); i++) {
    await fetch(`https://pokeapi.co/api/v2/pokemon/${i}`)
      .then((result) => result.json())
      .then((data) => {
        tempArr.push({
          name: data.species.name,
          cardImage: !data.sprites.front_default
            ? data.sprites.other["official-artwork"].front_default
            : data.sprites.front_default,
          clicked: false,
        })
      })
      .catch((err) => {
        error.value = err
      })
  }
  data.value = tempArr

  return { data, error }
}


const handleGameStart = async () => {
  const { data, error } = await fetchData()
  if (error.value) {
    console.log(error.value)
  }
  console.log(data)
  gameCardsArray.value = data.value

}
watchEffect(() => {
  handleGameStart()
}, [])

const arrayShuffler = (array: ICard[]) => {
  let shuffledArray: any = []
  let usedIndexes: number[] = []

  let i = 0
  while (i < array.length) {
    const RandNum = Math.floor(Math.random() * array.length)
    if (!usedIndexes.includes(RandNum)) {
      shuffledArray.push(array[RandNum])
      usedIndexes.push(RandNum)
      i++
    }
  }
  return shuffledArray
}

const cardClickHandler = (card: any) => {
  console.log(card)
  if (card.clicked) {
    lost.value = true
    console.log(card)
    twiceClickedCard.value = card.name
  }
  const newArray = gameCardsArray.value.map((crd) =>
    crd.name === card.name ? { ...crd, clicked: true } : crd
  )

  gameCardsArray.value = (arrayShuffler(newArray))
  round.value = round.value + 1

  console.log(gameCardsArray)
}



</script>

<template>
  <div>
    <div v-if="!lost">
      <p v-if="round == 1">
        You created a {{ rows }} x {{ cols }} grid, good luck! Round {{ round }} /
        {{ rows * cols }}
      </p>
      <p v-if="round !== 1">Round {{ round }} out of {{ cols * rows }}</p>

      <div :style="{
        display: `grid`, gridTemplateColumns: `repeat(${cols}, 1fr)`, gridTemplateRows: `repeat(${rows}, 1fr)`
      }">

        <Card v-for="card in   gameCardsArray" :card="card" :clickHandler="() => cardClickHandler(card)" />
      </div>
    </div>
    <div v-if="lost">
      <p>{{ twiceClickedCard }} was already clicked, do you want to play a new game?</p>
      <button @click="props.newGame()">New game</button>
    </div>
    <div v-if="won">
      <p>You Won, new game?</p>
      <button @click="props.newGame()">New game</button>

    </div>
  </div>
</template>

<style scoped>
.read-the-docs {
  color: #888;
}
</style>
