// src/Components/Card/Card.tsx
import "./Card.css"
import { ICard } from "../../App"

export default function Card({
  card,
  imgWidth,
  clickHandler,
}: {
  card: ICard
  imgWidth: number
  clickHandler: () => void
}) {
  const { name, cardImage } = card
  return (
    <div className="single-card" onClick={() => clickHandler()}>
      <img
        src={`${cardImage}`}
        alt={name}
        className="undraggable"
        style={{
          width: `${imgWidth}rem`,
        }}
      />
    </div>
  )
}

// src/components/Card.vue
<script setup lang="ts">
defineProps<{
    card: {
        name: string,
        cardImage: string,
        clicked: boolean,
    }, clickHandler: () => void
}>()

</script>

<template>
    <div className="single-card" v-on:click="clickHandler">
        <img :src="card.cardImage" :alt="card.name" class="undraggable" />
    </div>
</template>

<style scoped></style>
